### ISSUE TITLE
Syntax error in declaracad/editor/view.enaml

### ISSUE THREAD

**Issue by ceremcem** [codelv/declaracad#15]
After fixing some module importing issues in #14, `python main.py` throws the following error: 

```
python main.py 
2018-10-06 23:45:39,875 | DEBUG   | declaracad | Starting plugin 'declaracad.core'
2018-10-06 23:45:40,266 | DEBUG   | declaracad | Starting plugin 'declaracad.ui'
2018-10-06 23:45:40,288 | DEBUG   | declaracad | Starting plugin 'declaracad.docs'
2018-10-06 23:45:40,372 | DEBUG   | declaracad | Starting plugin 'declaracad.viewer'
Traceback (most recent call last):
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/parser/base_parser.py", line 199, in parse
    return self.parser.parse(source, debug=0, lexer=lexer)
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/ply/yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/ply/yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/parser/base_parser.py", line 3374, in p_error
    syntax_error(msg, FakeToken(lexer, t.lineno))
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/parser/base_lexer.py", line 71, in syntax_error
    _parsing_error(SyntaxError, message, token)
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/parser/base_lexer.py", line 55, in _parsing_error
    raise ParsingError(klass, message, info)
enaml.core.parser.base_lexer.ParsingError: ('invalid syntax', ('/home/ceremcem/declaracad/declaracad/editor/view.enaml', 317, 0, '    attr editor_font: str << f"{plugin.font_size}pt {plugin.font_family}"'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main()
  File "/home/ceremcem/declaracad/declaracad/__init__.py", line 47, in main
    launcher(args)
  File "/home/ceremcem/declaracad/declaracad/__init__.py", line 27, in launch_workbench
    workbench.main(**args.__dict__)
  File "/home/ceremcem/declaracad/declaracad/apps/workbench.py", line 59, in main
    workbench.run()
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/workbench/ui/ui_workbench.py", line 40, in run
    ui = self.get_plugin(UI_PLUGIN)
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/workbench/workbench.py", line 152, in get_plugin
    plugin.start()
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/workbench/ui/ui_plugin.py", line 60, in start
    self._start_autostarts()
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/workbench/ui/ui_plugin.py", line 397, in _start_autostarts
    workbench.get_plugin(autostart.plugin_id)
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/workbench/workbench.py", line 152, in get_plugin
    plugin.start()
  File "/home/ceremcem/declaracad/declaracad/ui/plugin.py", line 46, in start
    self._refresh_dock_items()
  File "/home/ceremcem/declaracad/declaracad/ui/plugin.py", line 126, in _refresh_dock_items
    DockItem = declaration.factory()
  File "/home/ceremcem/declaracad/declaracad/editor/manifest.enaml", line 190, in item_factory
    from .view import EditorDockItem
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/import_hooks.py", line 134, in load_module
    code, path = self.get_code()
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/import_hooks.py", line 409, in get_code
    return self.compile_code()
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/import_hooks.py", line 373, in compile_code
    ast = parse(self.read_source(), file_info.src_path)
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/parser/__init__.py", line 48, in parse
    return _parser.parse(enaml_source, filename)
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/parser/base_parser.py", line 201, in parse
    raise parse_error()
  File "/home/ceremcem/declaracad/declaracad/editor/view.enaml", line 317
    attr editor_font: str << f"{plugin.font_size}pt {plugin.font_family}"
    ^
SyntaxError: invalid syntax
```

**Comment by frmdstryr** [comment]
Thanks for reporting this. 

f-string support was recently added to enaml and is coming in 0.10.3 (not yet released).

Installing the latest version of enaml from git master branch should fix this.

**Comment by ceremcem** [comment]
> Installing the latest version of enaml from git master branch should fix this.

So shouldn't "Workaround" section of #14 solve the issue: 

>1. Create `requirements.txt` with the following contents: 
>
>```
>git+git://github.com/nucleic/atom
>git+https://github.com/nucleic/enaml
>```
>
>then upgrade the modules: 
>
>```
>pip install --upgrade -r requirements.txt
>```

**Comment by frmdstryr** [comment]
Yes, It sounds like that should work. 
Can confirm it installed this PR https://github.com/nucleic/enaml /pull/288

Since that isn't working for whatever reason simply changing the f string usage to an equivalent str.format() call string should do it.

Sorry I'm on my phone and cant help further at the moment

**Comment by frmdstryr** [comment]
enaml 0.10.3 was released with support for fstrings

**Comment by ceremcem** [comment]
Please reopen this issue as it's not resolved yet: 

```
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/core/import_hooks.py", line 134, in load_module
    code, path = self.get_code()
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/core/import_hooks.py", line 409, in get_code
    return self.compile_code()
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/core/import_hooks.py", line 373, in compile_code
    ast = parse(self.read_source(), file_info.src_path)
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/core/parser/__init__.py", line 48, in parse
    return _parser.parse(enaml_source, filename)
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/core/parser/base_parser.py", line 201, in parse
    raise parse_error()
  File "/home/ceremcem/declaracad/declaracad/editor/view.enaml", line 317
    attr editor_font: str << f"{plugin.font_size}pt {plugin.font_family}"
```

# Version 
```
(declaracad) ceremcem@cca-erik:declaracad$ git rev-parse --verify HEAD
b1427bea589a8b3345edfe9864a46cd05369dd6b
```

**Comment by frmdstryr** [comment]
Did you uninstall atom & enaml and reinstall `enaml==0.10.3`? Also I see miniconda2 but the lib says python3.6. Is it using python 3.6 or 2.7? I've had issues crossing versions like that before. 

If I change the fstring to a non-existant `g` string, this is the traceback I get: 

```python-traceback
  File "/home/user/miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/import_hooks.py", line 208, in exec_module
    code, _ = self.get_code()
  File "/home/user/miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/import_hooks.py", line 469, in get_code
    return self.compile_code()
  File "/home/user/miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/import_hooks.py", line 433, in compile_code
    ast = parse(self.read_source(), file_info.src_path)
  File "/home/user/miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/parser/__init__.py", line 48, in parse
    return _parser.parse(enaml_source, filename)
  File "/home/user/miniconda3/envs/declaracad/lib/python3.6/site-packages/enaml/core/parser/base_parser.py", line 201, in parse
    raise parse_error()
  File "/home/user/Workspace/declaracad/declaracad/editor/view.enaml", line 317
    attr editor_font: str << g"{plugin.font_size}pt {plugin.font_family}"
    ^
SyntaxError: invalid syntax
```
which is different. enaml should not use `load_module` on python 3 anymore (see https://github.com/nucleic/enaml/blob/master/enaml/core/import_hooks.py#L157-L164).

**Comment by ceremcem** [comment]
I didn't make any further attempts to solve the issue. I just update the dependencies just in case, update `declaracad` and install: 

```
source activate declaracad
conda install -c conda-forge -c dlr-sc -c pythonocc -c oce pythonocc-core==0.18.1
cd declaracad
git pull
pip install .
python main.py
```

Should I need to manually update any dependencies?

**Comment by frmdstryr** [comment]
Good point. Let me require `enaml>=0.10.3`

**Comment by frmdstryr** [comment]
Can you try now, it should install the correct version of enaml by default.

**Comment by ceremcem** [comment]
Nice!
